//DEPENDENCIES
const bands = require('express').Router()
const db = require('../models') //gives us access to all our models instead of requiring each one individually; must have the index.js generated by Sequelize CLI to do this
    //db.Band would access the Band model; since we'll want to access that model multiple times in this controller, we'll set Band = to the db
const { Band } = db
const { Op } = require('sequelize')

//INDEX
bands.get('/', async (req, res) => {
    try {
        const foundBands = await Band.findAll({
            where: {
                name: { [Op.like]: `%${req.query.name ? req.query.name: ''}%`}
            },
            order: [ ['available_start_time', 'ASC']]
        })
        res.status(200).json(foundBands)
    } catch(err) {
        console.log(err)
        res.status(500).json({message: 'Server error'})
    }
})

//SHOW
bands.get('/:id', async (req, res) => {
    try {
        const foundBand = await Band.findOne({
            where: { band_id: req.params.id }
        })
        res.status(200).json(foundBand)
    } catch(err) {
        console.log(err)
        res.status(500).json({message: 'Server error'})
    }
})

//CREATE
bands.post('/', async (req, res) => {
    try {
        const newBand = Band.create(req.body)
        res.status(201).json({message: 'Band created', data: newBand})
    } catch (err) {
        console.log(err)
        res.status(500).json({message: 'Server error'})
    }
})

//UPDATE
bands.put('/:id', async (req, res) => {
    try {
        const updatedBands = await Band.update(
            req.body, {
            where: {band_id: req.params.id}
        })
        res.status(200).json({message: `${updatedBands} bands updated`})
    } catch(err) {
        console.log(err)
        res.status(500).json({message: 'Server error'})
    }
})

//DELETE
bands.delete('/:id', async (req, res) => {
    try {
        const deletedBands = await Band.destroy({
                where: {band_id: req.params.id}
        })
        res.status(200).json({message: `${deletedBands} band(s) deleted`})
    } catch(err) {
        console.log(err)
        res.status(500).json({message: 'Server error'})
    }
})

//EXPORT
module.exports = bands