//DEPENDENCIES
const events = require('express').Router()
const db = require('../models') //gives us access to all our models instead of requiring each one individually; must have the index.js generated by Sequelize CLI to do this
const { Event } = db
const { Op } = require('sequelize')

//INDEX
events.get('/', async (req, res) => {
    try {
        const foundEvents = await Event.findAll({
            where: {
                name: { [Op.like]: `%${req.query.name ? req.query.name: ''}%`}
            },
            order: [ ['start_time', 'ASC']]
        })
        res.status(200).json(foundEvents)
    } catch(err) {
        console.log(err)
        res.status(500).json({message: 'Server error'})
    }
})

//SHOW
events.get('/:id', async (req, res) => {
    try {
        const foundEvent = await Event.findOne({
            where: { event_id: req.params.id }
        })
        res.status(200).json(foundEvent)
    } catch(err) {
        console.log(err)
        res.status(500).json({message: 'Server error'})
    }
})

//CREATE
events.post('/', async (req, res) => {
    try {
        const newEvent = Event.create(req.body)
        res.status(201).json({message: 'Event created', data: newEvent})
    } catch (err) {
        console.log(err)
        res.status(500).json({message: 'Server error'})
    }
})

//UPDATE
events.put('/:id', async (req, res) => {
    try {
        const updatedEvents = await Event.update(
            req.body, {
            where: {event_id: req.params.id}
        })
        res.status(200).json({message: `${updatedEvents} events updated`})
    } catch(err) {
        console.log(err)
        res.status(500).json({message: 'Server error'})
    }
})

//DELETE
events.delete('/:id', async (req, res) => {
    try {
        const deletedEvents = await Event.destroy({
                where: {event_id: req.params.id}
        })
        res.status(200).json({message: `${deletedEvents} event(s) deleted`})
    } catch(err) {
        console.log(err)
        res.status(500).json({message: 'Server error'})
    }
})

//EXPORT
module.exports = events