//DEPENDENCIES
const stages = require('express').Router()
const db = require('../models') //gives us access to all our models instead of requiring each one individually; must have the index.js generated by Sequelize CLI to do this
const { Stage } = db
const { Op } = require('sequelize')

//INDEX
stages.get('/', async (req, res) => {
    try {
        const foundStages = await Stage.findAll({
            where: {
                stage_name: { [Op.like]: `%${req.query.name ? req.query.name: ''}%`}
            }
        })
        res.status(200).json(foundStages)
    } catch(err) {
        console.log(err)
        res.status(500).json({message: 'Server error'})
    }
})

//SHOW
stages.get('/:id', async (req, res) => {
    try {
        const foundStage = await Stage.findOne({
            where: { stage_id: req.params.id }
        })
        res.status(200).json(foundStage)
    } catch(err) {
        console.log(err)
        res.status(500).json({message: 'Server error'})
    }
})

//CREATE
stages.post('/', async (req, res) => {
    try {
        const newStage = Stage.create(req.body)
        res.status(201).json({message: 'Stage created', data: newStage})
    } catch (err) {
        console.log(err)
        res.status(500).json({message: 'Server error'})
    }
})

//UPDATE
stages.put('/:id', async (req, res) => {
    try {
        const updatedStages = await Stage.update(
            req.body, {
            where: {stage_id: req.params.id}
        })
        res.status(200).json({message: `${updatedStages} stages updated`})
    } catch(err) {
        console.log(err)
        res.status(500).json({message: 'Server error'})
    }
})

//DELETE
stages.delete('/:id', async (req, res) => {
    try {
        const deletedStages = await Stage.destroy({
                where: {stage_id: req.params.id}
        })
        res.status(200).json({message: `${deletedStages} stage(s) deleted`})
    } catch(err) {
        console.log(err)
        res.status(500).json({message: 'Server error'})
    }
})

//EXPORT
module.exports = stages